### ISSUE TITLE
Segundo Articulo

### ISSUE THREAD

**Issue by angelpatinoamado** [angelpatinoamado/T_e_I_NEWS#3]
Noticia de Germán Parra

**Comment by angelpatinoamado** [comment]
Germán, necesito que trabaje sobre el documento README.md. No cree un nuevo archivo

**Comment by davidparra08** [comment]
si sr disculpe

**Comment by angelpatinoamado** [comment]
Listo Germán, su parte quedo bien. Ya puede hacer el pull request, para poder cerrar el issue y hacer merge.
