### ISSUE TITLE
Quinto Articulo 

### ISSUE THREAD

**Issue by angelpatinoamado** [angelpatinoamado/T_e_I_NEWS#9]
Noticia de Jorge Bayona

**Comment by AndresBayona15** [comment]
**Mendy seguirá encarcelado hasta enero de 2022**

El futbolista francés del Manchester City Benjamin Mendy, de 27 años, será juzgado en el Reino Unido a partir del 24 de enero de 2022 por las varias violaciones de las que se le acusa, anunció este viernes un juez británico. 

La fecha, que aún está sujeta a cambios, se fijó tras una vista en el juzgado de Chester, en el norte de Inglaterra, en que el internacional francés, campeón del mundo con Francia en 2018, sólo habló para identificarse.

Al final de la audiencia, que duró 45 minutos, Mendy permaneció en detención preventiva y al abandonar la sala le hizo un guiño a un hombre del público. 

Un segundo hombre, Louis Saha Matturie, de 40 años, también fue acusado en este caso y compareció junto al francés. Se le acusa de cuatro violaciones a tres personas entre abril y agosto. El 15 de noviembre está prevista una nueva vista en la que la abogada de Mendy afirmó que podría solicitar la retirada de los cargos.

En prisión preventiva desde finales de agosto, el francés está acusado de tres violaciones en octubre de 2020 y una violación en agosto de 2021 en su casa de Prestbury, en el condado de Cheshire. 

También se le acusa de agredir sexualmente a una mujer, siempre en su casa, a principios de enero de este año. Las presuntas agresiones conciernen a tres mujeres, una de ellas menor de edad.

El Manchester City, donde juega desde 2017, le había suspendido en agosto, minutos antes de que la policía anunciara que iba a comparecer ante un juez.

 El club pagó 52 millones de libras (70 millones de dólares, 60 millones de euros) por Mendy, que fue descubierto en el Marsella y pasó una temporada en el Mónaco, convirtiéndolo en el defensa más caro de la historia en ese momento.

**Comment by AndresBayona15** [comment]
Mendy seguirá encarcelado hasta enero de 2022

El futbolista francés del Manchester City Benjamin Mendy, de 27 años, será juzgado en el Reino Unido a partir del 24 de enero de 2022 por las varias violaciones de las que se le acusa, anunció este viernes un juez británico.

La fecha, que aún está sujeta a cambios, se fijó tras una vista en el juzgado de Chester, en el norte de Inglaterra, en que el internacional francés, campeón del mundo con Francia en 2018, sólo habló para identificarse.

Al final de la audiencia, que duró 45 minutos, Mendy permaneció en detención preventiva y al abandonar la sala le hizo un guiño a un hombre del público.

Un segundo hombre, Louis Saha Matturie, de 40 años, también fue acusado en este caso y compareció junto al francés. Se le acusa de cuatro violaciones a tres personas entre abril y agosto. El 15 de noviembre está previsto una nueva vista en la que la abogada de Mendy afirmó que podría solicitar la retirada de los cargos.

En preventiva desde finales de agosto, el francés está acusado de tres violaciones en octubre de 2020 y una violación en agosto de 2021 en su casa de Prestbury, en el condado de Cheshire.

También se le acusa de agredir sexualmente a una mujer, siempre en su casa, a principios de enero de este año. Las presuntas agresiones conciernen a tres mujeres, una de ellas menor de edad.

El Manchester City, donde juega desde 2017, le había suspendido en agosto, minutos antes de que la policía anunciara que iba a comparecer ante un juez.

El club pagó 52 millones de libras (70 millones de dólares, 60 millones de euros) por Mendy, que fue descubierto en el Marsella y pasó una temporada en el Mónaco, convirtiéndolo en el defensa más caro de la historia en ese momento.

**Comment by angelpatinoamado** [comment]
Listo Jorge, su parte quedo bien. Ya puede hacer el pull request, para poder cerrar el issue.
